/* gui_gtk4.c */
void gui_mch_update_tabline(void);
guicolor_T gui_mch_get_rgb(guicolor_T pixel);
GtkSettings *gui_gtk_get_settings();
void mch_set_mouse_shape(int shape);
void gui_gtk_get_pointer(GtkWidget *widget, gint *x, gint *y, GdkModifierType *state);
void gui_mch_getmouse(int *x, int *y);
void gui_mch_setmouse(int x, int y);
void gui_mch_mousehide(int hide);
void gui_gtk_get_screen_geom_of_win(GtkWidget *widget, int point_x, int point_y, int *screen_x, int *screen_y, int *width, int *height);
void gui_mch_get_screen_dimensions(int *screen_w, int *screen_h);
void gui_mch_clear_block(int row1arg, int col1arg, int row2arg, int col2arg);
void gui_mch_clear_all(void);
void gui_mch_flush(void);
void gui_mch_new_colors(void);
void gui_mch_delete_lines(int row, int num_lines);
void gui_mch_insert_lines(int row, int num_lines);
void gui_gtk_draw_sign_pixbuf(GdkPixbuf *sign, int row, int col, int sign_width, int sign_height, int width, int height, int xoffset, int yoffset);
void gui_mch_create_scrollbar(scrollbar_T *sb, int orient);
void gui_mch_destroy_scrollbar(scrollbar_T *sb);
void gui_mch_enable_scrollbar(scrollbar_T *sb, int flag);
void gui_mch_set_scrollbar_pos(scrollbar_T *sb, int x, int y, int w, int h);
int gui_mch_get_scrollbar_ypadding(void);
int gui_mch_get_scrollbar_xpadding(void);
Display *gui_mch_get_display(void);
void gui_mch_forked(void);
int gui_mch_init(void);
int gui_mch_open(void);
int gui_mch_get_winpos(int *x, int *y);
void gui_mch_set_winpos(int x, int y);
int gui_mch_maximized(void);
char_u *gui_mch_font_dialog(char_u *oldval);
void gui_mch_newfont(void);
void gui_mch_flash(int msec);
void gui_mch_iconify(void);
void gui_mch_set_foreground(void);
void gui_mch_set_shellsize(int width, int height, int min_width, int min_height, int base_width, int base_height, int direction);
void gui_mch_free_all(void);
void gui_mch_exit(int rc);
void clip_mch_request_selection(Clipboard_T *cbd);
void clip_mch_lose_selection(Clipboard_T *cbd);
int clip_mch_own_selection(Clipboard_T *cbd);
void clip_mch_set_selection(Clipboard_T *cbd);
int clip_gtk_owner_exists(Clipboard_T *cbd);
void gui_mch_menu_set_tip(vimmenu_T *menu);
void gui_mch_show_toolbar(int showit);
void gui_mch_toggle_tearoffs(int enable);
void gui_mch_show_popupmenu(vimmenu_T *menu);
void gui_gtk_set_mnemonics(int enable);
void gui_mch_destroy_menu(vimmenu_T *menu);
void gui_mch_enable_menu(int showit);
void gui_mch_menu_hidden(vimmenu_T *menu, int hidden);
void gui_mch_add_menu_item(vimmenu_T *menu, int idx);
void gui_mch_add_menu(vimmenu_T *menu, int idx);
void gui_make_popup(char_u *path_name, int mouse_pos);
void gui_mch_menu_grey(vimmenu_T *menu, int grey);
void gui_gtk_find_replace_dialog_create(char_u *arg, int do_replace);
/* vim: set ft=c : */
