/* gui_gtk_x11.c */
GtkSettings *gui_gtk_get_settings();
void gui_mch_free_all(void);
void gui_gtk_get_pointer(GtkWidget *widget, gint *x, gint *y, GdkModifierType *state);
void gui_gtk_init_socket_server(void);
void gui_gtk_uninit_socket_server(void);
void gui_gtk_update_window_manager_hints(int force_width, int force_height);
void gui_mch_update_tabline(void);
void gui_gtk_set_selection_targets(GdkAtom selection);
void gui_gtk_set_dnd_targets(void);
int gui_mch_init(void);
void gui_mch_forked(void);
void gui_mch_new_colors(void);
void gui_gtk_get_screen_geom_of_win(GtkWidget *wid, int point_x, int point_y, int *screen_x, int *screen_y, int *width, int *height);
void gui_mch_get_screen_dimensions(int *screen_w, int *screen_h);
int gui_mch_open(void);
void gui_mch_exit(int rc);
int gui_mch_get_winpos(int *x, int *y);
void gui_mch_set_winpos(int x, int y);
int gui_mch_maximized(void);
void gui_mch_newfont(void);
void gui_mch_set_shellsize(int width, int height, int min_width, int min_height, int base_width, int base_height, int direction);
void gui_mch_enable_menu(int showit);
void gui_mch_show_toolbar(int showit);
char_u *gui_mch_font_dialog(char_u *oldval);
int gui_get_x11_windis(Window *win, Display **dis);
Display *gui_mch_get_display(void);
void gui_mch_flash(int msec);
void gui_mch_iconify(void);
void gui_mch_set_foreground(void);
void gui_mch_flush(void);
void gui_mch_clear_block(int row1arg, int col1arg, int row2arg, int col2arg);
void gui_mch_clear_all(void);
void gui_mch_delete_lines(int row, int num_lines);
void gui_mch_insert_lines(int row, int num_lines);
void clip_mch_request_selection(Clipboard_T *cbd);
void clip_mch_lose_selection(Clipboard_T *cbd);
int clip_mch_own_selection(Clipboard_T *cbd);
void clip_mch_set_selection(Clipboard_T *cbd);
int clip_gtk_owner_exists(Clipboard_T *cbd);
void gui_mch_menu_grey(vimmenu_T *menu, int grey);
void gui_mch_menu_hidden(vimmenu_T *menu, int hidden);
void gui_mch_enable_scrollbar(scrollbar_T *sb, int flag);
guicolor_T gui_mch_get_rgb(guicolor_T pixel);
void gui_mch_getmouse(int *x, int *y);
void gui_mch_setmouse(int x, int y);
void gui_mch_mousehide(int hide);
void mch_set_mouse_shape(int shape);
void gui_gtk_draw_sign_pixbuf(GdkPixbuf *sign, int row, int col, int sign_width, int sign_height, int width, int height, int xoffset, int yoffset);
/* vim: set ft=c : */
