/* gui_gtk_common.c */
guint gui_gtk_timeout_add(int time, gboolean (*callback)(gpointer), int *flagp);
void gui_gtk_timeout_remove(guint timer);
int gui_gtk_modifiers_gdk2mouse(guint state);
int gui_gtk_modifiers_gdk2vim(guint state);
void gui_mch_update(void);
int gui_mch_early_init_check(int give_message);
int gui_mch_init_check(void);
void gui_mch_prepare(int *argc, char **argv);
int gui_mch_is_blinking(void);
int gui_mch_is_blink_off(void);
void gui_mch_set_blinking(long waittime, long on, long off);
void gui_mch_stop_blink(int may_call_gui_update_cursor);
void gui_mch_start_blink(void);
void gui_gtk_mainwin_destroy_cb(GObject *object, gpointer data);
void gui_mch_unmaximize(void);
void gui_gtk_pointer_enter();
void gui_gtk_pointer_leave();
void gui_gtk_focus_enter(GtkWidget *widget);
void gui_gtk_focus_leave();
void gui_mch_set_text_area_pos(int x, int y, int w, int h);
void gui_gtk_process_motion_notify(int x, int y, GdkModifierType state);
void gui_gtk_process_button_press(GtkWidget *widget, guint32 event_time, GdkEventType event_type, GdkModifierType event_modifiers_state, guint event_button, int x, int y);
void gui_gtk_process_button_release(GtkWidget *widget, guint32 event_time, GdkEventType event_type, GdkModifierType event_modifiers_state, guint event_button, int x, int y);
int gui_mch_wait_for_chars(long wtime);
int gui_mch_haskey(char_u *name);
gint gui_gtk_process_key_press(guint key_sym, guint state);
void gui_gtk_rebuild_text_context();
int gui_mch_adjust_charheight(void);
int gui_mch_init_font(char_u *font_name, int fontset);
GuiFont gui_mch_get_font(char_u *name, int report_error);
char_u *gui_mch_get_fontname(GuiFont font, char_u *name);
void gui_mch_free_font(GuiFont font);
void gui_mch_expand_font(optexpand_T *args, void *param, int (*add_match)(char_u *val));
guicolor_T gui_mch_get_color(char_u *name);
GdkRGBA color_to_rgba(guicolor_T color);
guicolor_T gui_mch_get_rgb_color(int r, int g, int b);
void gui_mch_set_fg_color(guicolor_T color);
void gui_mch_set_bg_color(guicolor_T color);
void gui_mch_set_sp_color(guicolor_T color);
int gui_gtk_draw_string_ext(int row, int col, char_u *s, int len, int flags, int force_pango);
int gui_gtk_draw_string(int row, int col, char_u *s, int len, int flags);
void gui_mch_beep(void);
void gui_mch_invert_rectangle(int r, int c, int nr, int nc);
void gui_mch_draw_hollow_cursor(guicolor_T color);
void gui_mch_draw_part_cursor(int w, int h, guicolor_T color);
void gui_gtk_surface_copy_rect(int dest_x, int dest_y, int src_x, int src_y, int width, int height);
void gui_gtk_settings_xft_dpi_changed_cb(GtkSettings *gtk_settings, GParamSpec *pspec, gpointer data);
void gui_mch_drawsign(int row, int col, int typenr);
void *gui_mch_register_sign(char_u *signfile);
void gui_mch_destroy_sign(void *sign);
gboolean gui_gtk_draw_gui_surface_to_widget_surface(cairo_t *cr);
gboolean gui_gtk_should_ignore_tabline_event();
void gui_gtk_ignore_tabline_event(gboolean newsetting);
void gui_mch_show_tabline(int showit);
void gui_mch_set_curtab(int nr);
int gui_mch_showing_tabline(void);
void gui_mch_settitle(char_u *title, char_u *icon);
void gui_mch_set_dark_theme(int dark);
int lookup_menu_iconfile(char_u *iconfile, char_u *dest);
GtkWidget *gui_gtk_themed_menu_icon(vimmenu_T *menu, GtkIconSize icon_size);
GtkWidget *gui_gtk_stock_menu_icon(vimmenu_T *menu, GtkIconSize icon_size);
GtkWidget *gui_gtk_create_menu_icon(vimmenu_T *menu, GtkIconSize icon_size);
void gui_mch_draw_menubar(void);
char_u *gui_gtk_translate_mnemonic_tag(char_u *name, int use_mnemonic);
void gui_mch_set_scrollbar_thumb(scrollbar_T *sb, long val, long size, long max);
void gui_mch_find_dialog(exarg_T *eap);
void gui_mch_replace_dialog(exarg_T *eap);
const char *gui_gtk_convert_localized_message(char_u **buffer, const char *message);
void ex_helpfind(exarg_T *eap);
int gui_mch_dialog(int type, char_u *title, char_u *message, char_u *buttons, int def_but, char_u *textfield, int ex_cmd);
char_u *gui_mch_browse(int saving, char_u *title, char_u *dflt, char_u *ext, char_u *initdir, char_u *filter);
char_u *gui_mch_browsedir(char_u *title, char_u *initdir);
/* vim: set ft=c : */
